### ISSUE TITLE
Separate Repositories

### ISSUE THREAD

**Issue by colevandersWands** [feridunAKYOL/Javascript-30#4]
@feridunAKYOL,  For these exercises the goal is to practice creating full projects from scratch in  teams.

Instead of having all of them in this repository, create a new repository for each and link to the repo in the list at the bottom of the README.  this way you can practice on a clean repository for each project, creating a new project board, and not getting cluttered up with way too many branches

**Comment by feridunAKYOL** [comment]
@colevandersWands thank you... I have created a new repo for each :+1:
